#!/usr/bin/env bash
# Script that transfers a file from our client to a server.

if [ $# -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
if
# assigning parameters with variable
path_to_file=$1
ip=$2
username=$3
path-to_ssh_key=$4

#t transfer the file to the user home directory ~/
scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2":~/"
#check for trans_file

if [ $? -eq 0]
then
	echo "success file transfer"
else
	echo "sorry check your command-code "
if
