#!/usr/bin/env bash
#command to install nginx on web
 sudo  apt-get update
 sudo  apt-get install nginx
 sudo  ufw 'nginx HTTP'
 sudo  nginx -t 
 echo "Hello World!" | sudo tree /var/www/html/index.html
 sudo  service nginx reload
