#!/usr/bin/env bash
# Fix for service (init) must say that nginx is not running ← for real
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#sudo cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak creat back up
sudo sed -i 's,pid /run/nginx.pid, pid /run/nginx.bak,' /etc/nginx/nginx.conf
